### ISSUE TITLE
Request for a compiled jar

### ISSUE THREAD

**Issue by ZapikCZ** [NEMESIS13cz/Evercraft#1]
Hey! I get that you probably haven't cared for this for a long while, but do you still, by any chance, have the mod compiled as a jar stored somewhere?

There was a download link on Minecraft Forums years back, but they had to delete a lot of threads, including yours, due to EU's GDPR legal stuff.

Would be greatly appreciated if you know you have it. Don't search for it if you're pressed for time, I don't want to be a bother. I'm just really confused on how I would compile it myself and thought this might be a lesa headache-inducing alternative, at least for me.

Again, if you don't care, totally fine, I'll probably figure it out hopefully. I loved your mod back then, wanted to play with it again.

Thanks for reading this, if you ever do!

**Comment by Nemezor** [comment]
Sorry for the late reply, this isn't maintained at all.

I added the latest release to [releases](https://github.com/Nemezor/Evercraft/releases/tag/0.17dev3), a few things are a little buggy (power cables really don't like loops) while item transport pipes are completely broken and don't work, other than that the rest of the mod should work, though I recommend you use the "Recommended" release of Forge for 1.7.10 instead of "Latest", I remember there were some issues with that.

Thanks for your interest in Evercraft, even though it's dead! 😃

**Comment by ZapikCZ** [comment]
Yes! Thank you so much for this!
